### ISSUE TITLE
The vibration setting in the audio settings cannot be used

### ISSUE THREAD

**Issue by sonhak-18** [TheParasiteProject/bionic#1]
Hi, glad to provide you with feedback. I have a minor issue with your source ROM. Yes, the vibration setting cannot be used (force close). Are you aware of this issue? I think this is not an issue originating from my device. This is all I want to say, if you are interested I will send you the log. Thank You

**Comment by someone5678** [comment]
Thanks for suggesting issue!
Currently, all my devices correctly open vib settings.
I'll test it again later as I'm currently working on QPR3!
If you want, as you suggested, please attach log here! I'll check it after QPR3 merge done!!
